decrement:
  description: Decrement the value of an input number entity by its stepping.
  fields:
    entity_id: 
      description: Entity id of the input number that should be decremented.
      example: input_number.threshold
increment:
  description: Increment the value of an input number entity by its stepping.
  fields:
    entity_id: 
      description: Entity id of the input number that should be incremented.
      example: input_number.threshold
set_value:
  description: Set the value of an input number entity.
  fields:
    entity_id: 
      description: Entity id of the input number to set the new value.
      example: input_number.threshold
    value:
      description: The target value the entity should be set to.
      example: 42
set_min:
  description: Set the minimum allowable input input_number.
  fields:
    entity_id: 
      description: Entity id of the input number to recieve the new minimum.
      example: input_number.threshold
    value: 
      description: >
        The target value the entity's minimum range should be set to. If the
        entity's current value is below the new minimum, then the entity's
        value will be clamped to the new minimum.
      example: 40
set_max:
  description: Set the maximum allowable input input_number.
  fields:
    entity_id: 
      description: Entity id of the input number to recieve the new maximum.
      example: input_number.threshold
    value: 
      description: >
        The target value the entity's maximum range should be set to. If the
        entity's current value is above the new maximum, then the entity's
        value will be clamped to the new maximum.
      example: 45
