
- alias: Normalize Temperature
  initial_state: true
  trigger:
  - entity_id: sensor.ecobee_spread
    platform: state
  condition:
  - condition: numeric_state
    entity_id: sensor.ecobee_spread
    above: 2.0
  action:
  - service: climate.set_fan_mode
    data_template:
      entity_id: climate.thermostat
      fan_mode: >-
        {%- if (state_attr('climate.thermostat', 'current_temperature')|float >= 67.0)
            and (states('sensor.ecobee_spread')|float > 3.0) -%}
          on
        {%- else -%}
          off
        {%- endif -%}
  id: normalize_temperature


- id: auto_start_register_booster
  alias: Auto Start Register Booster
  trigger:
  - entity_id: climate.thermostat
    platform: state
  condition:
  - condition: template
    value_template: >-
      {{- is_state_attr("climate.thermostat", "hvac_action", "cooling") or 
          (states('sensor.office_temperature')|float >= 77.0)
      -}}
  - condition: device
    device_id: ad80753855d64fbfb84fa35223d54bb5
    domain: switch
    entity_id: switch.register_booster_plug_switch
    type: is_off
  action:
  - entity_id: switch.register_booster_plug_switch
    service: switch.turn_on
  initial_state: true
- id: auto_stop_register_booster
  alias: Auto Stop Register Booster
  trigger:
  - entity_id: climate.thermostat
    platform: state
  condition:
  - condition: template
    value_template: >-
      {{- (not is_state_attr("climate.thermostat", "hvac_action", "cooling") | int) and (
      states('sensor.office_temperature')|float < 77.0 ) -}}
  - condition: device
    device_id: ad80753855d64fbfb84fa35223d54bb5
    domain: switch
    entity_id: switch.register_booster_plug_switch
    type: is_on
  action:
  - entity_id: switch.register_booster_plug_switch
    service: switch.turn_off
  initial_state: true


- alias: Listen to CDs started from Harmony Hub
  initial_state: true
  trigger:
    platform: state
    entity_id: remote.family_room_harmony_hub
  condition:
    condition: template
    value_template: "{{-\n  trigger is defined and trigger.to_state is not none\n\
      \  and trigger.to_state.attributes is not none\n  and trigger.to_state.attributes.current_activity\
      \ == \"Listen to CDs\"\n-}}"
  action:
    service: switch.turn_on
    entity_id: switch.denon_cd_plug_switch
  id: 0135cb5921284e4787091873eb245f06

- alias: Listen to CDs ended from Harmony Hub
  initial_state: true
  trigger:
    platform: state
    entity_id: remote.family_room_harmony_hub
  condition:
    condition: template
    value_template: "{{- \n  trigger is defined \n  and trigger.from_state is not\
      \ none\n  and trigger.from_state.attributes is not none \n  and trigger.from_state.attributes.current_activity\
      \ == \"Listen to CDs\" \n-}}"
  action:
    service: switch.turn_off
    entity_id: switch.denon_cd_plug_switch
  id: 689ac6077a2f43578a4078871d416a75


- alias: Casting to Yamaha RX-V475
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.family_room_speaker
    to: playing
  - platform: state
    entity_id: media_player.everywhere
    to: playing
  - platform: state
    entity_id: media_player.upstairs_audio
    to: playing
  - platform: state
    entity_id: media_player.not_the_bedroom
    to: playing
  condition:
    condition: template
    value_template: "{{-\n  trigger is defined\n  and trigger.from_state is defined\n\
      \  and trigger.from_state.state != 'playing'\n-}}"
  action:
  - service: media_player.select_source
    data:
      entity_id: media_player.rx_v475_a16974
      source: AV4
  - condition: state
    entity_id: media_player.rx_v475_a16974
    state: 'off'
  - service: media_player.turn_on
    data:
      entity_id: media_player.rx_v475_a16974
  id: fb582d1acf324c77bcdd43f08fc2e4dd

- alias: Powering off Yamaha RX-V475
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.rx_v475_a16974
    from: 'on'
    to: 'off'
  condition:
    condition: template
    value_template: '{{- not is_state("media_player.chromecast", "off") -}}'
  action:
    service: media_player.media_pause
    data:
      entity_id: media_player.family_room_speaker
  id: 6a964c94c92f49b699d258c2a018e1e3


- alias: Casting to Onkyo TX-RZ820
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.onkyo_txrz820_4f772a
    to: playing
  condition:
    condition: template
    value_template: "{{-\n  not is_state_attr(\"remote.family_room_harmony_hub\",\
      \ \"current_activity\", \"Network Music\")\n-}}"
  action:
    service: remote.turn_on
    data:
      entity_id: remote.family_room_harmony_hub
      activity: Network Music
  id: df5f52f3006d4b1ca9d64ecbded66987


- alias: Casting to SHIELD
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.shield
    to: playing
  condition:
    condition: template
    value_template: "{{-\n  not is_state_attr(\"remote.family_room_harmony_hub\",\
      \ \"current_activity\",\n  \"SHIELD TV\")\n-}}"
  action:
    service: remote.turn_on
    data:
      entity_id: remote.family_room_harmony_hub
      activity: SHIELD TV
  id: f9812165edca4dfeb19ca130fbaa00dc
- alias: Casting to SHIELD ended from Harmony Hub
  initial_state: true
  trigger:
  - platform: state
    entity_id: remote.family_room_harmony_hub
  condition:
    condition: template
    value_template: "{{-\n  trigger is defined\n  and trigger.from_state is not none\n\
      \  and trigger.from_state.attributes is not none\n  and trigger.from_state.attributes.current_activity\
      \ == \"SHIELD TV\"\n-}}"
  action:
  - service: media_player.media_stop
    data:
      entity_id: media_player.shield
  - service: media_player.turn_off
    data:
      entity_id: media_player.shield
  id: a141efb59e9f429c9671c0033dcfe027


- alias: Casting to Family Room
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.chromecast
    to: playing
  condition:
    condition: template
    value_template: |-
      {{- not is_state_attr("remote.family_room_harmony_hub", "current_activity", "Chromecast") -}}
  action:
    service: remote.turn_on
    data:
      entity_id: remote.family_room_harmony_hub
      activity: Chromecast
  id: 123e9a5ea0d24d8982760adf1a5bf685

- alias: Casting to Family Room ended from Harmony Hub
  initial_state: true
  trigger:
  - platform: state
    entity_id: remote.family_room_harmony_hub
  condition:
    condition: template
    value_template: |-
      {{-
      trigger is defined and
      trigger.to_state.attributes.current_activity != "Chromecast" and 
      trigger.from_state.attributes.current_activity == "Chromecast" 
      -}}
  action:
  - service: media_player.media_pause
    data:
      entity_id: media_player.chromecast
  id: 580aacc8e53241ae94ff165b2a9e6469


- alias: Fridge Temperature Warning
  id: fridge_alarm
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.fridge_temperature
  condition:
    condition: template
    value_template: "{%- if is_state('sensor.fridge_temperature', 'unknown') -%}\n\
      \  false\n{%- else -%}\n  {%- set t = states('sensor.fridge_temperature')|float\
      \ -%}\n  {{- 33.0 > t or t > 42.0 -}}\n{%- endif -%}\""
  action:
    service: persistent_notification.create
    data:
      notification_id: warning_fridge_temperature
      message: Fridge temperature  {{states.sensor.fridge_temperature.state_with_unit}}
        at {{now().strftime('%c')}}!
      title: Fridge Temp out of Range!


- alias: Garage Warning
  id: garage_warning
  initial_state: true
  trigger:
    platform: state
    entity_id: cover.linear_nortek_security_control_llc_gd00z_4_garage_door_opener_remote_controller_barrier_state_label
    to: open
    for:
      minutes: 15
  condition:
    condition: template
    value_template: "{{-\n  not is_state(\n    \"cover.linear_nortek_security_control_llc_gd00z_4_garage_door_opener_remote_controller_barrier_state_label\"\
      ,\n    \"closed\")\n-}}"
  action:
    service: persistent_notification.create
    data_template:
      notification_id: garage_warning
      title: Garage Door is {{ states('cover.linear_nortek_security_control_llc_gd00z_4_garage_door_opener_remote_controller_barrier_state_label')|title
        }}!
      message: The garage door has been {{ states('cover.linear_nortek_security_control_llc_gd00z_4_garage_door_opener_remote_controller_barrier_state_label')
        }} for at least 15 minutes, consider closing it.


- id: sync_front_door_unlocked
  trigger:
  - entity_id: sensor.kwikset_front_door_alarm_type
    platform: state
    to: '19'
  - entity_id: sensor.kwikset_front_door_alarm_type
    platform: state
    to: '22'
  condition:
  - condition: state
    entity_id: lock.kwikset_front_door
    state: locked
  action:
  - data:
      entity_id: lock.kwikset_front_door
    service: lock.unlock
  initial_state: true
- id: sync_front_door_locked
  trigger:
  - entity_id: sensor.kwikset_front_door_alarm_type
    platform: state
    to: '18'
  - entity_id: sensor.kwikset_front_door_alarm_type
    platform: state
    to: '21'
  - entity_id: sensor.kwikset_front_door_alarm_type
    platform: state
    to: '27'
  condition:
  - condition: state
    entity_id: lock.kwikset_front_door
    state: unlocked
  action:
    data:
      entity_id: lock.kwikset_front_door
    service: lock.lock
  initial_state: true


- id: autolock_front_door
  alias: Autolock Front Door
  trigger:
  - entity_id: lock.kwikset_front_door
    for:
      minutes: 30
    platform: state
    to: unlocked
  condition:
  - condition: state
    entity_id: lock.kwikset_front_door
    state: unlocked
  action:
  - data:
      entity_id: lock.kwikset_front_door
    service: lock.lock
  initial_state: true


- alias: Turn on Porch Light when motion detected
  id: outdoor_motion
  initial_state: true
  trigger:
    platform: numeric_state
    entity_id: sensor.front_porch_motion_sensor_alarm_level
    above: 0
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: or
      conditions:
      - condition: state
        entity_id: light.switch_front_porch_light
        state: 'off'
      - condition: state
        entity_id: timer.outdoor_motion
        state: active
  action:
  - service: light.turn_on
    data:
      entity_id: light.switch_front_porch_light
  - service: timer.start
    data:
      entity_id: timer.outdoor_motion
      duration: 00:05:00


- alias: Turn off Porch Light after motion timeout
  id: motion_timeout
  initial_state: true
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.outdoor_motion
  action:
  - service: light.turn_off
    data:
      entity_id: light.switch_front_porch_light


- id: propagate_kitchen_light
  trigger:
    - platform: event
      event_type: automation_reloaded
    - platform: state
      entity_id: light.switch_kitchen_lights
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: light.switch_kitchen_lights
      from: 'on'
      to: 'off'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.switch_kitchen_lights
        state: 'on'
      - condition: state
        entity_id: light.switch_kitchen_lights
        state: 'off'
  action:
    - service_template: 'light.turn_{{- states("light.switch_kitchen_lights") -}}'
      entity_id: light.cree_connected_a_19_60w_equivalent_c11b0bfe_level_on_off
