---
default_config:

homeassistant:
  # Load packages
  packages: !include_dir_named packages
  # Customization file
  customize: !include customize.yaml
  
logger:
  default: warn
  logs:
    homeassistant.components.rest: warn
    homeassistant.components.rest_command: warn
    homeassistant.components.rest_cmd: debug
    homeassistant.components.mqtt: warn
    homeassistant.components.harmony: warn
    homeassistant.components.lutron_caseta: warn

lovelace:
  mode: storage
  dashboards:
    ho-me:
      mode: yaml
      title: Dashboard
      icon: mdi:script
      show_in_sidebar: true
      filename: ui-lovelace.yaml

api:

alexa:
  smart_home:
    filter:
      include_entities:
        - light.living_room_floor_lamp
        - light.cree_connected_a_19_60w_equivalent_663b0afe_level_on_off
        - light.cree_connected_a_19_60w_equivalent_c11b0bfe_level_on_off

# Monitor system health
system_health:

# Monitor Device Presence
device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_host
    ssl: true
    verify_ssl: false
    username: !secret ddwrt_admin_username
    password: !secret ddwrt_admin_password
    interval_seconds: 15
    consider_home: 180
    new_device_defaults:
      track_new_devices: true

# Can't use Bluetooth since I don't have bluetooth adapter on this hardware
#  - platform: bluetooth_tracker
#  - platform: bluetooth_le_tracker

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# https://www.home-assistant.io/components/http/
http: !include secret.http.yaml

timer:
  outdoor_motion:
    duration: '00:00:15'

# Discover some devices automatically
discovery:
  ignore: []

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_keep_days: 8
  db_url: !secret recorder_db_url

# Sensors
sensor:
  # Weather prediction
  #- platform: yr

  # Track the moon
  - platform: moon

  # Raspberry Pi System Resources
  - platform: systemmonitor
    resources:
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: memory_use_percent
      - type: swap_use_percent

  # Custom Sensors
  - platform: template
    sensors:
      environment:
        friendly_name: 'Environment'
        value_template: !secret ENVIRONMENT

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Switches
switch:
  - platform: wake_on_lan
    name: Alder PC
    host: alder.lan
    mac: !secret alder_mac1
  - platform: wake_on_lan
    name: Trogdor PC
    host: trogdor.lan
    mac: !secret trogdor_mac1
  - platform: wake_on_lan
    name: Karen PC
    host: KAREN-PC.lan
    mac: !secret karen_mac1
  - platform: template
    switches:
      all_audio:
        friendly_name: "All Audio"
        value_template: >-
          {{ is_state('group.media_player_avr', 'on') }}
        icon_template: mdi:boombox
        turn_off:             
          - service: homeassistant.turn_off
            data_template:
              entity_id:
                - group.media_player_avr
                - group.media_player_cast
        turn_on:
          - service: homeassistant.turn_on
            data_template:
              entity_id: 
                - group.media_player_avr

group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
