title: Home
views:
  - path: home
    title: Home
    cards:

      - title: Front Porch
        id: front_porch
        show_header_toggle: false
        type: entities
        entities:
          - lock.kwikset_front_door
          - light.switch_front_porch_light
          - entity: sensor.front_porch_motion_sensor_temperature
            name: Temperature
          - entity: binary_sensor.motion_sensor_home_security_motion_detection
            name: Motion

      - title: Garage
        id: garage
        type: entities
        show_header_toggle: false
        entities:
          - entity: cover.linear_nortek_security_control_llc_gd00z_4_garage_door_opener_remote_controller_barrier_state_label

      - type: entities
        title: Whole House
        id: whole_house
        entities:        
          - entity: switch.occupancy
          - entity: switch.all_audio
          - entity: scene.exterior_on
          - entity: scene.interior_on
          - entity: scene.lights_out
          - entity: sensor.ecobee_spread
          - entity: automation.normalize_temperature_2
          - entity: switch.thermostat_fan_mode
          - entity: media_player.everywhere

      - title: Thermostat
        id: thermostat
        type: thermostat
        entity: climate.thermostat_2

      - title: Entryway
        id: entryway
        show_header_toggle: false
        type: entities
        entities:
          - light.switch_front_foyer_chandelier

      - title: Kitchen
        id: kitchen
        show_header_toggle: false
        type: entities
        entities:
          - light.switch_kitchen_lights
          - light.cree_connected_a_19_60w_equivalent_c11b0bfe_level_on_off

      - title: Dining Room
        id: dining_room
        show_header_toggle: false
        type: entities
        entities:
          - light.dining_room_chandelier

      - title: Family Room
        id: family_room
        show_header_toggle: false
        type: entities
        entities:
          - scene.media
          - light.family_room_floor_lamp
          - light.family_room_landing
          - remote.family_room_harmony_hub
          - media_player.downstairs_tx_rz820
          - media_player.shield
          - media_player.chromecast
          - media_player.rz820
          - media_player.tonysroku3
          - switch.denon_cd_plug_switch
          - entity: sensor.family_room_temperature
          - entity: binary_sensor.family_room_occupancy

      - title: Living Room
        id: living_room
        show_header_toggle: false
        type: entities
        entities:
          - light.living_room_table
          - light.living_room_floor_lamp
          - light.christmas_tree
          - sensor.thermostat_current_temperature
          - sensor.thermostat_current_humidity
          - binary_sensor.thermostat_occupancy

      - title: Top of Stairs
        id: top_of_stairs
        show_header_toggle: false
        type: entities
        entities:
          - light.upstairs_hallway_landing
          - media_player.upstairs

      - title: Office
        id: office
        show_header_toggle: false
        type: entities
        entities:
          - light.office_sconce
          - light.cree_connected_a_19_60w_equivalent_663b0afe_level_on_off
          - light.office_lights
          - entity: switch.cable_modem_plug_switch
          - media_player.office_chromecast
          - media_player.rx_v475_a16974
          - sensor.office_temperature
          - binary_sensor.office_occupancy
          - switch.register_booster_plug_switch
          - automation.auto_start_register_booster
          - switch.honeywell_unknown_type_4f50_id_3034_switch_2

      - type: entities
        title: Master Bedroom
        id: master_bedroom
        show_header_toggle: false
        entities:
          - entity: light.master_bedroom_cove_lights
          - entity: switch.audioengine_a2_plug_switch
          - entity: switch.hank_electronics_ltd_hkzw_so03_smart_plug_switch
          - entity: media_player.master_bedroom
          - entity: sensor.lil_bee_temperature
          - entity: binary_sensor.lil_bee_occupancy

      - title: OpenEVSE
        id: openevse
        type: entities
        show_header_toggle: false
        entities:
          - entity: switch.openevse_enablement
          - entity: sensor.openevse_state
          - entity: sensor.openevse_current_now
          - entity: sensor.openevse_session_energy
          - entity: sensor.openevse_service_level
          - entity: sensor.openevse_pilot
          - entity: number.openevse_pilot
          - entity: sensor.openevse_energy_limit
          - entity: number.openevse_charge_limit
          - entity: script.openevse_rapi_gh

  - title: Media
    cards:
      - type: entities
        title: Chromecast Radio
        show_header_toggle: False
        id: radio
        icon: mdi:radio
        entities:
          - input_select.chromecast_radio_station
          - input_text.custom_station
          - input_select.chromecast_radio_speakers
          - input_number.volume_radio
          - script.play_chromecast_radio
          - script.stop_chromecast_radio

      - type: entities
        title: Control
        show_header_toggle: False
        id: harmony
        icon: mdi:remote
        entities:
          - remote.family_room_harmony_hub
          - remote.tonysroku3
          - remote.tonys_office_roku

# **START** Media Player Conditionals
#
# {% for state in states.media_player %}
#       - type: conditional
#         conditions:
#           - entity: {{state.entity_id}}
#             state_not: "off"
#           - entity: {{state.entity_id}}
#             state_not: "unknown"
#           - entity: {{state.entity_id}}
#             state_not: "unavailable"
#         card:
#           type: media-control
#           entity: {{state.entity_id}}
# {%- endfor %}
#
      - type: conditional
        conditions:
          - entity: media_player.chromecast
            state_not: "off"
          - entity: media_player.chromecast
            state_not: "unknown"
          - entity: media_player.chromecast
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.chromecast
      - type: conditional
        conditions:
          - entity: media_player.downstairs
            state_not: "off"
          - entity: media_player.downstairs
            state_not: "unknown"
          - entity: media_player.downstairs
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.downstairs
      - type: conditional
        conditions:
          - entity: media_player.downstairs_tx_rz820
            state_not: "off"
          - entity: media_player.downstairs_tx_rz820
            state_not: "unknown"
          - entity: media_player.downstairs_tx_rz820
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.downstairs_tx_rz820
      - type: conditional
        conditions:
          - entity: media_player.downstairs_tx_rz820_zone_2
            state_not: "off"
          - entity: media_player.downstairs_tx_rz820_zone_2
            state_not: "unknown"
          - entity: media_player.downstairs_tx_rz820_zone_2
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.downstairs_tx_rz820_zone_2
      - type: conditional
        conditions:
          - entity: media_player.downstairs_tx_rz820_zone_3
            state_not: "off"
          - entity: media_player.downstairs_tx_rz820_zone_3
            state_not: "unknown"
          - entity: media_player.downstairs_tx_rz820_zone_3
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.downstairs_tx_rz820_zone_3
      - type: conditional
        conditions:
          - entity: media_player.everywhere
            state_not: "off"
          - entity: media_player.everywhere
            state_not: "unknown"
          - entity: media_player.everywhere
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.everywhere
      - type: conditional
        conditions:
          - entity: media_player.home_assistant
            state_not: "off"
          - entity: media_player.home_assistant
            state_not: "unknown"
          - entity: media_player.home_assistant
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.home_assistant
      - type: conditional
        conditions:
          - entity: media_player.kitchen_speaker
            state_not: "off"
          - entity: media_player.kitchen_speaker
            state_not: "unknown"
          - entity: media_player.kitchen_speaker
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.kitchen_speaker
      - type: conditional
        conditions:
          - entity: media_player.master_bedroom
            state_not: "off"
          - entity: media_player.master_bedroom
            state_not: "unknown"
          - entity: media_player.master_bedroom
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.master_bedroom
      - type: conditional
        conditions:
          - entity: media_player.not_the_bedroom
            state_not: "off"
          - entity: media_player.not_the_bedroom
            state_not: "unknown"
          - entity: media_player.not_the_bedroom
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.not_the_bedroom
      - type: conditional
        conditions:
          - entity: media_player.office_chromecast
            state_not: "off"
          - entity: media_player.office_chromecast
            state_not: "unknown"
          - entity: media_player.office_chromecast
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.office_chromecast
      - type: conditional
        conditions:
          - entity: media_player.rx_v475_a16974
            state_not: "off"
          - entity: media_player.rx_v475_a16974
            state_not: "unknown"
          - entity: media_player.rx_v475_a16974
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.rx_v475_a16974
      - type: conditional
        conditions:
          - entity: media_player.rz820
            state_not: "off"
          - entity: media_player.rz820
            state_not: "unknown"
          - entity: media_player.rz820
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.rz820
      - type: conditional
        conditions:
          - entity: media_player.samsung_pn60f8500
            state_not: "off"
          - entity: media_player.samsung_pn60f8500
            state_not: "unknown"
          - entity: media_player.samsung_pn60f8500
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.samsung_pn60f8500
      - type: conditional
        conditions:
          - entity: media_player.shield
            state_not: "off"
          - entity: media_player.shield
            state_not: "unknown"
          - entity: media_player.shield
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.shield
      - type: conditional
        conditions:
          - entity: media_player.tonysroku3
            state_not: "off"
          - entity: media_player.tonysroku3
            state_not: "unknown"
          - entity: media_player.tonysroku3
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.tonysroku3
      - type: conditional
        conditions:
          - entity: media_player.upstairs
            state_not: "off"
          - entity: media_player.upstairs
            state_not: "unknown"
          - entity: media_player.upstairs
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.upstairs

# **END** Media Player Conditionals

  - title: Outside
    cards:
      - title: Weather from Ecobee
        id: weather-ecobee
        type: weather-forecast
        entity: weather.thermostat
      - title: Outside
        id: outside
        type: entities
        entities:
          - sun.sun
          - sensor.airnow_aqi

  - title: System
    cards:
      - title: System
        id: system
        type: entities
        entities:
          - switch.karen_pc
          - switch.alder_pc
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
          - entity: sensor.memory_use_percent
          - entity: sensor.processor_use
          - entity: sensor.swap_use_percent

