views:
  - title: Home
    cards:

      - title: Front Porch
        id: front_porch
        show_header_toggle: false
        type: entities
        entities:
          - lock.kwikset_front_door
          - light.switch_front_porch_light
          - entity: sensor.vision_zp3102_pir_motion_sensor_temperature
            name: Temperature
          - entity: sensor.vision_zp3102_pir_motion_sensor_alarm_level
            name: Motion

      - title: Garage
        id: garage
        type: entities
        show_header_toggle: false
        entities:
          - entity: cover.linear_gd00z4_garage_door_opener_remote_controller_barrier_state_label

# **START** Media Player Conditionals
      - type: conditional
        conditions:
          - entity: media_player.downstairs_tx_rz820
            state_not: "off"
          - entity: media_player.downstairs_tx_rz820
            state_not: "unknown"
        card:
          type: media-control
          entity: media_player.downstairs_tx_rz820
      - type: conditional
        conditions:
          - entity: media_player.downstairs_tx_rz820_zone_2
            state_not: "off"
          - entity: media_player.downstairs_tx_rz820_zone_2
            state_not: "unknown"
        card:
          type: media-control
          entity: media_player.downstairs_tx_rz820_zone_2
      - type: conditional
        conditions:
          - entity: media_player.downstairs_tx_rz820_zone_3
            state_not: "off"
          - entity: media_player.downstairs_tx_rz820_zone_3
            state_not: "unknown"
        card:
          type: media-control
          entity: media_player.downstairs_tx_rz820_zone_3
      - type: conditional
        conditions:
          - entity: media_player.everywhere
            state_not: "off"
          - entity: media_player.everywhere
            state_not: "unknown"
          - entity: media_player.everywhere
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.everywhere
      - type: conditional
        conditions:
          - entity: media_player.tv_room_acc
            state_not: "off"
          - entity: media_player.tv_room_acc
            state_not: "unknown"
          - entity: media_player.tv_room_acc
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.tv_room_acc
      - type: conditional 
        conditions:
          - entity: media_player.onkyo_tx_rz820_4f772a
            state_not: "off"
          - entity: media_player.onkyo_tx_rz820_4f772a
            state_not: "unknown"
          - entity: media_player.onkyo_tx_rz820_4f772a
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.onkyo_tx_rz820_4f772a
      - type: conditional
        conditions:
          - entity: media_player.master_bedroom_acc
            state_not: "off"
          - entity: media_player.master_bedroom_acc
            state_not: "unknown"
          - entity: media_player.master_bedroom_acc
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.master_bedroom_acc
      - type: conditional
        conditions:
          - entity: media_player.shield
            state_not: "off"
          - entity: media_player.shield
            state_not: "unknown"
          - entity: media_player.shield
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.shield
      - type: conditional
        conditions:
          - entity: media_player.upstairs
            state_not: "off"
          - entity: media_player.upstairs
            state_not: "unknown"
          - entity: media_player.upstairs
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.upstairs
      - type: conditional
        conditions:
          - entity: media_player.office_chromecast
            state_not: "off"
          - entity: media_player.office_chromecast
            state_not: "unknown"
          - entity: media_player.office_chromecast
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.office_chromecast
      - type: conditional
        conditions:
          - entity: media_player.rx_v475_a16974
            state_not: "off"
          - entity: media_player.rx_v475_a16974
            state_not: "unknown"
        card:
          type: media-control
          entity: media_player.rx_v475_a16974
#      - type: conditional
#        conditions:
#          - entity: media_player.samsung_pdp60_pn60f8500
#            state_not: "off"
#          - entity: media_player.samsung_pdp60_pn60f8500
#            state_not: "unknown"
#        card:
#          type: media-control
#          entity: media_player.samsung_pdp60_pn60f8500
      - type: conditional
        conditions:
          - entity: media_player.tonys_office_roku
            state_not: "off"
          - entity: media_player.tonys_office_roku
            state_not: "unknown"
          - entity: media_player.tonys_office_roku
            state_not: "idle"
        card:
          type: media-control
          entity: media_player.tonys_office_roku
      - type: conditional
        conditions:
          - entity: media_player.tonysroku3
            state_not: "off"
          - entity: media_player.tonysroku3
            state_not: "unknown"
          - entity: media_player.tonysroku3
            state_not: "idle"
        card:
          type: media-control
          entity: media_player.tonysroku3
# **END** Media Player Conditionals

      - type: entities
        title: Chromecast Radio
        show_header_toggle: False
        id: radio
        icon: mdi:radio
        entities:
          - input_select.chromecast_radio_station
          - input_text.custom_station
          - input_select.chromecast_radio_speakers
          - input_number.volume_radio
          - script.play_chromecast_radio
          - script.stop_chromecast_radio

      - type: entities
        title: Whole House
        id: whole_house
        entities:        
          - entity: switch.occupancy
          - entity: switch.all_audio
          - entity: scene.exterior_on
          - entity: scene.interior_on
          - entity: scene.lights_out
          - entity: sensor.ecobee_spread
          - entity: automation.normalize_temperature
          - entity: switch.thermostat_fan_mode
          - entity: media_player.everywhere

      - title: Dining Room
        id: dining_room
        show_header_toggle: false
        type: entities
        entities:
          - light.dining_room_chandelier

      - title: Entryway
        id: entryway
        show_header_toggle: false
        type: entities
        entities:
          - light.switch_front_foyer_chandelier

      - title: Family Room
        id: family_room
        show_header_toggle: false
        type: entities
        entities:
          - scene.tv_lights
          - light.family_room_floor_lamp
          - light.family_room_landing
          - remote.family_room_harmony_hub
          - media_player.downstairs_tx_rz820
          - entity: media_player.shield
        #   - entity: media_player.onkyo_txrz820_4f772a
        #     name: Chromecast Audio Built-in
          - media_player.tonysroku3
          - switch.denon_cd

      - title: Kitchen
        id: kitchen
        show_header_toggle: false
        type: entities
        entities:
          - light.switch_kitchen_lights
          - entity: sensor.fridge_temperature
            icon: mdi:fridge-outline

      - title: Living Room
        id: living_room
        show_header_toggle: false
        type: entities
        entities:
          - light.living_room_table
          - light.switch_living_room_floor_lamp
          - sensor.thermostat_temperature
          - sensor.thermostat_humidity
          - binary_sensor.thermostat_occupancy

      - title: Office
        id: office
        show_header_toggle: false
        type: entities
        entities:
          - light.hank_hkzwrgb01_rgb_bulb_level
          - switch.hank_hkzwso03_smart_plug_switch
          - entity: switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch_2
            name: Tower Fan
          - media_player.office_chromecast
          - media_player.tonys_office_roku
          - media_player.rx_v475_a16974
          - sensor.office_temperature
          - binary_sensor.office_occupancy
          - switch.register_booster
          - automation.run_register_booster

      - title: Top of Stairs
        id: top_of_stairs
        show_header_toggle: false
        type: entities
        entities:
          - light.upstairs_hallway_landing
          - media_player.upstairs

      - type: entities
        title: Master Bedroom
        id: master_bedroom
        show_header_toggle: false
        entities:
          - entity: light.master_bedroom_cove_lights
          - entity: switch.hank_hkzwso03_smart_plug_switch_2
          - entity: media_player.master_bedroom_acc
          - entity: sensor.lil_bee_temperature
          - entity: binary_sensor.lil_bee_occupancy

      - title: Thermostat
        id: thermostat
        type: thermostat
        entity: climate.thermostat

      - title: Weather
        id: weather
        type: weather-forecast
        entity: weather.dark_sky

      - title: Outside
        id: outside
        type: entities
        entities:
          - sun.sun
          - entity: weather.dark_sky
            name: Weather by Dark Sky
          - entity: weather.thermostat
            name: Weather by Ecobee

      - title: OpenEVSE
        id: openevse
        type: entities
        show_header_toggle: false
        entities:
          - entity: switch.openevse_enable
          - entity: switch.openevse_divertmode
          - entity: sensor.openevse_state
          - entity: sensor.openevse_pilot_current
          - entity: sensor.openevse_charging_current
          - entity: sensor.openevse_session_energy
          - entity: input_select.openevse_service_level
          - entity: input_number.openevse_current
          - entity: automation.set_openevse_max_current
          - entity: switch.openevse_save_current

      - title: System
        id: system
        type: entities
        entities:
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
          - entity: sensor.memory_use_percent
          - entity: sensor.processor_use
          - entity: sensor.swap_use_percent
