views:
  - title: Home
    cards:

# **START** Media Player Conditionals
      - type: conditional
        conditions:
          - entity: media_player.downstairs_txrz820
            state_not: "off"
          - entity: media_player.downstairs_txrz820
            state_not: "unknown"
        card:
          type: media-control
          entity: media_player.downstairs_txrz820
      - type: conditional
        conditions:
          - entity: media_player.downstairs_txrz820_zone_2
            state_not: "off"
          - entity: media_player.downstairs_txrz820_zone_2
            state_not: "unknown"
        card:
          type: media-control
          entity: media_player.downstairs_txrz820_zone_2
      - type: conditional
        conditions:
          - entity: media_player.downstairs_txrz820_zone_3
            state_not: "off"
          - entity: media_player.downstairs_txrz820_zone_3
            state_not: "unknown"
        card:
          type: media-control
          entity: media_player.downstairs_txrz820_zone_3
      - type: conditional
        conditions:
          - entity: media_player.everywhere_
            state_not: "off"
          - entity: media_player.everywhere_
            state_not: "unknown"
          - entity: media_player.everywhere_
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.everywhere_
      - type: conditional
        conditions:
          - entity: media_player.family_room_tv
            state_not: "off"
          - entity: media_player.family_room_tv
            state_not: "unknown"
          - entity: media_player.family_room_tv
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.family_room_tv
      - type: conditional
        conditions:
          - entity: media_player.master_bedroom_
            state_not: "off"
          - entity: media_player.master_bedroom_
            state_not: "unknown"
          - entity: media_player.master_bedroom_
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.master_bedroom_
      - type: conditional
        conditions:
          - entity: media_player.shield
            state_not: "off"
          - entity: media_player.shield
            state_not: "unknown"
          - entity: media_player.shield
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.shield
      - type: conditional
        conditions:
          - entity: media_player.o_p
            state_not: "off"
          - entity: media_player.o_p
            state_not: "unknown"
          - entity: media_player.o_p
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.o_p
      - type: conditional
        conditions:
          - entity: media_player.office_
            state_not: "off"
          - entity: media_player.office_
            state_not: "unknown"
          - entity: media_player.office_
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.office_
      - type: conditional
        conditions:
          - entity: media_player.onkyo_txrz820_4f772a
            state_not: "off"
          - entity: media_player.onkyo_txrz820_4f772a
            state_not: "unknown"
          - entity: media_player.onkyo_txrz820_4f772a
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.onkyo_txrz820_4f772a
      - type: conditional
        conditions:
          - entity: media_player.portable
            state_not: "off"
          - entity: media_player.portable
            state_not: "unknown"
          - entity: media_player.portable
            state_not: "unavailable"
        card:
          type: media-control
          entity: media_player.portable
      - type: conditional
        conditions:
          - entity: media_player.rxv475_a16974
            state_not: "off"
          - entity: media_player.rxv475_a16974
            state_not: "unknown"
        card:
          type: media-control
          entity: media_player.rxv475_a16974
#      - type: conditional
#        conditions:
#          - entity: media_player.samsung_pdp60_pn60f8500
#            state_not: "off"
#          - entity: media_player.samsung_pdp60_pn60f8500
#            state_not: "unknown"
#        card:
#          type: media-control
#          entity: media_player.samsung_pdp60_pn60f8500
      - type: conditional
        conditions:
          - entity: media_player.tonys_office_roku
            state_not: "off"
          - entity: media_player.tonys_office_roku
            state_not: "unknown"
          - entity: media_player.tonys_office_roku
            state_not: "idle"
        card:
          type: media-control
          entity: media_player.tonys_office_roku
      - type: conditional
        conditions:
          - entity: media_player.tonysroku3
            state_not: "off"
          - entity: media_player.tonysroku3
            state_not: "unknown"
          - entity: media_player.tonysroku3
            state_not: "idle"
        card:
          type: media-control
          entity: media_player.tonysroku3
      #- type: conditional
      #  conditions:
      #    - entity: media_player.upstairs_tx8050
      #      state_not: "off"
      #    - entity: media_player.upstairs_tx8050
      #      state_not: "unknown"
      #  card:
      #    type: media-control
      #    entity: media_player.upstairs_tx8050
# **END** Media Player Conditionals

      - type: entities
        title: Chromecast Radio
        id: radio
        icon: mdi:radio
        entities:
          - input_select.chromecast_radio_station
          - input_text.custom_station
          - input_select.chromecast_radio_speakers
          - input_number.volume_radio
          - script.play_chromecast_radio
          - script.stop_chromecast_radio

      - type: entities
        title: Whole House
        id: whole_house
        entities:
          - entity: switch.all_audio
          - entity: scene.exterior_on
          - entity: scene.interior_on
          - entity: scene.lights_out
          - entity: scene.goodbye
          - entity: sensor.ecobee_spread
          - entity: automation.normalize_temperature
          - entity: switch.thermostat_fan_mode
          - entity: media_player.everywhere_

      - title: Dining Room
        id: dining_room
        show_header_toggle: false
        type: entities
        entities:
          - light.dining_room_chandelier

      - title: Entryway
        id: entryway
        show_header_toggle: false
        type: entities
        entities:
          - light.switch_front_foyer_chandelier

      - title: Family Room
        id: family_room
        show_header_toggle: false
        type: entities
        entities:
          - scene.tv_lights
          - light.family_room_floor_lamp
          - light.family_room_landing
          - remote.family_room_harmony_hub
          - media_player.downstairs_txrz820
          - entity: media_player.shield
          - entity: media_player.family_room_tv
            name: Chromecast Video
          - entity: media_player.onkyo_txrz820_4f772a
            name: Chromecast Audio Built-in
          - media_player.tonysroku3
          - switch.denon_cd

      - title: Front Porch
        id: front_porch
        show_header_toggle: false
        type: entities
        entities:
          - light.switch_front_porch_light
          - entity: sensor.vision_zp3102_pir_motion_sensor_temperature
            name: Temperature
          - entity: sensor.vision_zp3102_pir_motion_sensor_alarm_level
            name: Motion

      - title: Kitchen
        id: kitchen
        show_header_toggle: false
        type: entities
        entities:
          - light.switch_kitchen_lights
          - entity: sensor.fridge_temperature
            icon: >-
              {% if is_state('sensor.fridge_temperature', 'unknown') %}
                mdi:help-circle-outline
              {% else %}
                {% if states('sensor.fridge_temperature')|float < 33.0 %}
                  mdi:snowflake
                {% else %}
                  {% if states('sensor.fridge_temperature')|float > 37.0 %}
                    mdi:fire
                  {% else %}
                    mdi:fridge-outline
                  {% endif %}
                {% endif %}
              {% endif %}
          - binary_sensor.fridge_occupancy

      - title: Living Room
        id: living_room
        show_header_toggle: false
        type: entities
        entities:
          - light.living_room_table
          - light.switch_living_room_floor_lamp
          - sensor.thermostat_temperature
          - sensor.thermostat_humidity
          - binary_sensor.thermostat_occupancy

      - title: Office
        id: office
        show_header_toggle: false
        type: entities
        entities:
          - light.hank_hkzwrgb01_rgb_bulb_level
          - media_player.office_
          - media_player.tonys_office_roku
          - media_player.rxv475_a16974
          - sensor.office_temperature
          - binary_sensor.office_occupancy

      - title: Top of Stairs
        id: top_of_stairs
        show_header_toggle: false
        type: entities
        entities:
          - light.upstairs_hallway_landing

      - type: entities
        title: Master Bedroom
        id: master_bedroom
        show_header_toggle: false
        entities:
          - entity: light.master_bedroom_cove_lights
          - entity: switch.hank_hkzwso03_smart_plug_switch_2
          #- entity: media_player.upstairs_tx8050
          - entity: media_player.master_bedroom_
          - entity: sensor.lilbee_temperature
          - entity: binary_sensor.lilbee_occupancy
      - title: Garage
        id: garage
        type: entities
        show_header_toggle: false
        entities:
          - cover.linear_gd00z4_garage_door_opener_remote_controller_barrier_state_label
          - sensor.openevse_state
          - sensor.openevse_total_energy
          - sensor.openevse_pilot_current
          - sensor.openevse_charging_current
          - sensor.openevse_session_energy
          - sensor.openevse_temp_1

      - title: Thermostat
        id: thermostat
        type: thermostat
        entity: climate.thermostat

      - title: Weather
        id: weather
        type: weather-forecast
        entity: weather.dark_sky

      - title: Outside
        id: outside
        type: entities
        entities:
          - sun.sun
          - entity: weather.dark_sky
            name: Weather by Dark Sky
          - entity: weather.thermostat
            name: Weather by Ecobee

      - title: System
        id: system
        type: entities
        entities:
          - entity: sensor.load_1m
          - entity: sensor.load_5m
          - entity: sensor.load_15m
          - entity: sensor.memory_use_percent
          - entity: sensor.processor_use
          - entity: sensor.swap_use_percent
