---
# In order to use this, you must have the following configurations created in 
# the base configuration.yaml:
#   MQTT
#
# You must also be using the "openevse" topic in the 
# OpenEVSE control panel (or edit secrets per below.)
#
# Required Secret  -->  Example:
#   OPENEVSE_HOST:      "myhost"
#   OPENEVSE_USERNAME:  "myuser"
#   OPENEVSE_PASSWORD:  "mypasswd"
#   OPENEVSE_R_GU:      'http://myhost/r?json=1&rapi=$GU'
#   OPENEVSE_R_GC:      'http://myhost/r?json=1&rapi=$GC'
#   OPENEVSE_R_STATUS:  'http://myhost/status'
#   OPENEVSE_T_TEMP1:   "openevse/temp1"
#   OPENEVSE_T_AMP:     "openevse/amp"
#   OPENEVSE_T_PILOT:   "openevse/pilot"
#   OPENEVSE_T_WH:      "openevse/wh"
#   OPENEVSE_T_STATE:   "openevse/state"
#   OPENEVSE_T_IFS:     "openevse/rapi/in/$FS"
#   OPENEVSE_T_IFE:     "openevse/rapi/in/$FE"
#   OPENEVSE_T_ISC:     "openevse/rapi/in/$SC"
#   OPENEVSE_T_ISL:     "openevse/rapi/in/$SL"
#   OPENEVSE_T_DIVERT:  'openevse/divertmode/set'

# Sensors
sensor:
  # Use OpenEVSE RAPI API to Retrieve the active charging energy
  # https://www.home-assistant.io/components/sensor.rest/
  # Example: 
  #  curl --digest --user 'user:pass' 'http://myhost/r?json=1&rapi=$GU'
  #  $OK 40629846 165327^27
#   - platform: rest
#     name: "OpenEVSE RAPI $GU"
#     resource: !secret OPENEVSE_R_GU
#     force_update: no
#     authentication: basic
#     username: !secret OPENEVSE_USERNAME
#     password: !secret OPENEVSE_PASSWORD
#     headers:
#         User-Agent: Home Assistant
#         Content-Type: application/json
#     json_attributes: [ 'cmd', 'ret' ]
#     value_template: >-
#       {{- state_attr("sensor.openevse_rapi_gu", "ret") -}}
  
  # Get OpenEVSE min/max current from RAPI
  - platform: rest
    name: "OpenEVSE RAPI $GC"
    resource: !secret OPENEVSE_R_GC
    force_update: no
    authentication: basic
    username: !secret OPENEVSE_USERNAME
    password: !secret OPENEVSE_PASSWORD
    headers:
        User-Agent: Home Assistant
        Content-Type: application/json
    json_attributes: [ 'cmd', 'ret' ]
    value_template: >-
      {{- state_attr("sensor.openevse_rapi_gc", "ret") -}}

  - platform: rest
    name: "OpenEVSE Status"
    resource: !secret OPENEVSE_R_STATUS
    force_update: yes
    authentication: basic
    username: !secret OPENEVSE_USERNAME
    password: !secret OPENEVSE_PASSWORD
    headers:
        User-Agent: Home Assistant
        Content-Type: application/json
    json_attributes: [ "mode", "wifi_client_connected","srssi" , "ipaddress","emoncms_connected","packets_sent","packets_success","mqtt_connected" , "ohm_hour","free_heap","comm_sent","comm_success","amp","pilot","temp1","temp2","temp3","state","elapsed","wattsec","watthour","gfcicount","nogndcount","stuckcount","divertmode","solar","grid_ie","charge_rate","divert_update"]
    value_template: >-
      {{- state_attr("sensor.openevse_status", "state") -}}

  # The RAPI REST Sensor is very unreliable, so filter it
  - platform: filter
    name: "OpenEVSE Session Energy"
    entity_id: sensor.openevse_session_energy_raw
    filters:
      - filter: outlier
        window_size: 6
        radius: 0.5

  # Custom Sensors
  - platform: template
    sensors:
      openevse_session_energy_raw:
        friendly_name: "OpenEVSE Session Energy (status)"
        icon_template: mdi:gauge
        unit_of_measurement: 'kWh'
        entity_id: sensor.openevse_status
        value_template: >-
          {%- if state_attr('sensor.openevse_status', 'wattsec') == 'unknown'
              or state_attr('sensor.openevse_status', 'wattsec') is none -%}
            unknown
          {%- else -%}
            {%- set wattsec = state_attr('sensor.openevse_status', 'wattsec') -%}
            {{- (wattsec|float / 3600000)|round(2) -}}
          {%- endif -%}

    #   openevse_session_energy_rest:
    #     friendly_name: "OpenEVSE Session Energy (rapi)"
    #     icon_template: mdi:gauge
    #     unit_of_measurement: 'kWh'
    #     entity_id: sensor.openevse_rapi_gu
    #     value_template: >-
    #       {%- if state_attr('sensor.openevse_rapi_gu', 'ret') == 'unknown'
    #           or state_attr('sensor.openevse_rapi_gu', 'ret') is none -%}
    #         unknown
    #       {%- else -%}
    #         {%- set rgx = '(?<=^\$OK )[0-9]+' -%}
    #         {%- if ret|regex_search(rgx) -%}
    #           {%- set v = ret | regex_findall_index(rgx) -%}
    #           {{- (v|float / 3600000)|round(2) -}}
    #         {%- else -%}
    #           unknown
    #         {%- endif -%}
    #       {%- endif -%}

      openevse_state:
        friendly_name: "OpenEVSE State"
        icon_template: >-
          {%- if states('sensor.openevse_mqtt_state') | regex_match('^[01]$') -%}
            mdi:power-plug-off
          {%- elif is_state('sensor.openevse_mqtt_state', '2') -%}
            mdi:car-electric
          {%- elif is_state('sensor.openevse_mqtt_state', '3') -%}
            mdi:battery-charging
          {%- elif states('sensor.openevse_mqtt_state') | regex_match('^([456789]|10)$') -%}
            mdi:battery-alert
          {%- elif is_state('sensor.openevse_mqtt_state', '254') -%}
            mdi:sleep
          {%- elif is_state('sensor.openevse_mqtt_state', '255') -%}
            mdi:power-off
          {%- else -%}
            mdi:battery-unknown
          {%- endif -%}
        value_template: >-
          {%- if states('sensor.openevse_mqtt_state') | regex_match('^[01]$') -%}
            Not Connected
          {%- elif is_state('sensor.openevse_mqtt_state', '2') -%}
            Connected
          {%- elif is_state('sensor.openevse_mqtt_state', '3') -%}
            Charging
          {%- elif states('sensor.openevse_mqtt_state') | regex_match('^([456789]|10)$') -%}
            Error ({{- states('sensor.openevse_mqtt_state') -}})
          {%- elif is_state('sensor.openevse_mqtt_state', '254') -%}
            Sleeping
          {%- elif is_state('sensor.openevse_mqtt_state', '255') -%}
            Disabled
          {%- else -%}
            Unknown ({{- states('sensor.openevse_mqtt_state') -}})
          {%- endif -%}

  # OpenEVSE MQTT Tracker
  - platform: mqtt
    name: "OpenEVSE Temp 1"
    state_topic: !secret OPENEVSE_T_TEMP1
    unit_of_measurement: '°F'
    device_class: temperature
    value_template: >-
      {%- macro C2F(temperature) -%}
      {% set tmp = (((temperature *9) /50.0) + 32) %}
      {{- "%0.2f" % tmp -}}
      {%- endmacro -%}
      {{- C2F(value|float)|float -}}

  - platform: mqtt
    name: "OpenEVSE Charging Current"
    icon: mdi:current-ac
    state_topic: !secret OPENEVSE_T_AMP
    unit_of_measurement: "A"
    value_template: >-
      {{- (value|float / 1000.0) | round(1) -}}

  - platform: mqtt
    name: "OpenEVSE Pilot Current"
    icon: mdi:current-ac
    state_topic: !secret OPENEVSE_T_PILOT
    unit_of_measurement: "A"
    value_template: >-
      {{- value|int -}}

  - platform: mqtt
    name: "OpenEVSE Total Energy"
    icon: mdi:gauge-full
    state_topic: !secret OPENEVSE_T_WH
    unit_of_measurement: "kWh"
    value_template: >-
      {{- value|float / 1000 | round(2) -}}

  - platform: mqtt
    name: "OpenEVSE MQTT State"
    state_topic: !secret OPENEVSE_T_STATE

# Switches
switch:
  - platform: template
    switches:
      openevse_enable:
        friendly_name: "OpenEVSE Enable"
        turn_off:
          - service: mqtt.publish
            data:
              topic: !secret OPENEVSE_T_IFS
        turn_on:
          - service: mqtt.publish
            data:
              topic: !secret OPENEVSE_T_IFE
        icon_template: >-
          {%- if states('sensor.openevse_mqtt_state') | regex_match('^[0123]$') -%}
            mdi:power-plug
          {%- else -%}
            mdi:sleep
          {%- endif -%}
        value_template: >-
          {{- states('sensor.openevse_mqtt_state') | regex_match('^[0123]$') -}}
      openevse_divertmode:
        friendly_name: "OpenEVSE Eco Divert"
        turn_off:
          - service: mqtt.publish
            data:
              topic: !secret OPENEVSE_T_DIVERT
              retain: true
              payload: 1
        turn_on:
          - service: mqtt.publish
            data:
              topic: !secret OPENEVSE_T_DIVERT
              retain: true
              payload: 2
        icon_template: mdi:solar-power
        value_template: >-
          {{- state_attr('sensor.openevse_status', 'divertmode') == 2 -}}

input_number:
  openevse_current:
    name: "OpenEVSE Current"
    unit_of_measurement: "A"
    min: 10
    max: 40
    step: 1

input_select:
  # Requires use of custom input_select component
  openevse_service_level:
    name: OpenEVSE Service Level
    options:
      - Auto
      - Level 1
      - Level 2
    values:
      - "A"
      - "1"
      - "2"
    icon: mdi:target

automation old:
  - alias: Update OpenEVSE Min/Max Current
    id: update_openevse_min_max_current
    trigger:
      platform: state
      entity_id: sensor.openevse_rapi_gc
    condition:
      condition: template
      value_template: >-
        {{ state_attr('sensor.openevse_rapi_gc', 'ret') | regex_match('^\$OK [0-9]+ +[0-9]+') }}
    action:
      - service: input_number.set_min
        data_template:
          entity_id: input_number.openevse_current
          # Restrict the min to 6A - 10A
          value: >-
            {%- set ret = state_attr('sensor.openevse_rapi_gc', 'ret') -%}
            {%- set rgx = '(?<=^\$OK) +([0-9]+) +([0-9]+)' -%}
            {%- set v = ret | regex_findall_index(rgx) -%}
            {{- [10, [6, v[0]|int]|max] | min -}}
      - service: input_number.set_max
        data_template:
          entity_id: input_number.openevse_current
          # Restrict the max to 40A even if L2 returns >40A
          value: >-
            {%- set ret = state_attr('sensor.openevse_rapi_gc', 'ret') -%}
            {%- set rgx = '(?<=^\$OK )([0-9]+) +([0-9]+)' -%}
            {%- set v = ret | regex_findall_index(rgx) -%}
            {{- [40, v[1]|int]|min -}}

  - alias: Update OpenEVSE Charge Current
    id: update_openevse_charge_current
    trigger:
      platform: state
      entity_id: sensor.openevse_pilot_current
    condition:
      condition: template
      value_template: >-
        {{- states('sensor.openevse_pilot_current') | regex_match('^[0-9]+$') -}}
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.openevse_current
        value: >-
          {{- states('sensor.openevse_pilot_current')|int -}}

  - alias: Set OpenEVSE Charge Current
    id: set_openevse_charge_current
    trigger:
      platform: state
      entity_id: input_number.openevse_current
    action:
      service: mqtt.publish
      data_template:
        topic: !secret OPENEVSE_T_ISC
        retain: true
        # Set temporary current value if trailing "V" after power
        # e.g.: `payload: 23 V`
        payload: >-
          {{- states('input_number.openevse_current')|int }}

  - alias: Update OpenEVSE Service Level
    id: update_openevse_service_level
    trigger:
      platform: mqtt
      topic: !secret OPENEVSE_T_ISL
    action:
      service: input_select.select_option
      data_template:
        entity_id: input_select.openevse_service_level
        option: >-
          {% for option in state_attr("input_select.openevse_service_level", "values") -%}
            {% if trigger.payload == option -%}
              {{ state_attr("input_select.openevse_service_level", 'options')[loop.index - 1] }}
            {%- endif %}
          {%- endfor %}
          
  - alias: Set OpenEVSE Service Level
    id: set_openevse_service_level
    trigger:
      platform: state
      entity_id: input_select.openevse_service_level
    action:
      service: mqtt.publish
      data_template:
        topic: !secret OPENEVSE_T_ISL
        retain: true
        payload: >-
          {% for option in state_attr("input_select.openevse_service_level", "options") -%}
            {% if is_state("input_select.openevse_service_level", option) -%}
              {{ state_attr("input_select.openevse_service_level", 'values')[loop.index - 1] }}
            {%- endif %}
          {%- endfor %}
